### ISSUE TITLE
Can't compile solutions

### ISSUE THREAD

**Issue by AnthonerMonzon** [wolfyreload/OpenChords#17]
Hi I got this problem while compiling the solution:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file '<mypath>\OpenChords-2.4.0\OpenChords\OpenChords.CrossPlatform\bin\Release\OpenChords.CrossPlatform.dll' could not be found	OpenChords.CrossPlatform.Executable	<mypath>\OpenChords-2.4.0\OpenChords\OpenChords.CrossPlatform.Executable\CSC	1	Active

**Comment by wolfyreload** [comment]
Hi Anthoner,

I have found the issue. Building OpenChords requires a tool called **Pandoc** to be installed (its used to building the OpenChords help files). I have updated the build to include **Pandoc** in a nuget package in the **develop** branch. 

Please check it out and see if it solves your issue.

**Comment by AnthonerMonzon** [comment]
Hi MIchael,

Thanks for the reply and updates, I also have this error: 
The command "<my path>\OpenChords-develop\OpenChords\Manual\MakeHelpDocument.bat
" exited with code 9009.	OpenChords.CrossPlatform		

Best Regards...

**Comment by wolfyreload** [comment]
Hi Anthoner,

The MakeHelpDocument.bat requires the nuget package **Pandoc.Windows.2.1.0** before it can run.

Please try force all the nuget packages to load by selecting the "Restore Nuget Packages" option in Visual Studio
![Restore Nuget Packages](https://user-images.githubusercontent.com/5320719/44968774-17690780-af4a-11e8-85b2-ca7a7e5181c6.png) 
Then try running the application.

It should be restoring all nuget packages by default but that doesn't seem to be the case.

**Comment by AnthonerMonzon** [comment]
Hi Michael,

Yes I have restored the Nuget, but still got the error:

![image](https://user-images.githubusercontent.com/14208403/44975142-3ee4c200-af94-11e8-8061-7a23a6b6e772.png)

**Comment by AnthonerMonzon** [comment]
Hi Michael,

BTW I remove the Pre-build event command for OpenChords.CrossPlatform and it build and run:
![image](https://user-images.githubusercontent.com/14208403/44976187-fe3a7800-af96-11e8-85f7-7d28eb6a4711.png)

**Comment by wolfyreload** [comment]
Strange. Glad you came right

**Comment by AnthonerMonzon** [comment]
Hi Michael,

Actually I encounter this with other projects that I have done, usually I send all my folder with bin, including the compiled dll etc., or vice versa
