### ISSUE TITLE
Thanks for a good program under a free open source license

### ISSUE THREAD

**Issue by mrkaban** [wolfyreload/OpenChords#18]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7/openchords-%D0%B0%D0%BA%D0%BA%D0%BE%D1%80%D0%B4%D1%8B.html).

The project is interesting, so please don't abandon it!

Will the releases be published here or on SourceForge?

**Comment by wolfyreload** [comment]
Hi mrkaban,

I saw your message and forgot to reply. Sorry :) Development for OpenChords comes in waves, at present I'm only really fixing bugs rather than adding additional functionality.

I typically put the releases on both here and sourceforge

**Comment by wolfyreload** [comment]
And good point, I see that I haven't deployed the latest version here. This has been resolved.
